routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::name('dashboard.')->namespace('Dashboard')->prefix('dashboard')->group(function () {
    // Controllers Within The "App\Http\Controllers\Dashboard" Namespace
    Route::get('/product', 'ProductController@index')->name('product');
    Route::get('/product/add', 'ProductController@create')->name('add-product');
    Route::post('/product/add', 'ProductController@store');
    Route::get('/product/{id}', 'ProductController@edit')->name('show-product');
    Route::post('/product/{id}', 'ProductController@update');
    Route::get('/product/delete/{id}', 'ProductController@destroy')->name('delete-product');
});

resources/views/layouts/admin-panel.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ asset('bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('bower_components/font-awesome/css/font-awesome.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset('bower_components/Ionicons/css/ionicons.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('dist/css/AdminLTE.min.css') }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
    folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('dist/css/skins/_all-skins.min.css') }}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{{ asset('bower_components/morris.js/morris.css') }}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{ asset('bower_components/jvectormap/jquery-jvectormap.css') }}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{ asset('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{ asset('bower_components/bootstrap-daterangepicker/daterangepicker.css') }}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{ asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    {{-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic"> --}}
    <meta name="csrf-token" content="{{ csrf_token() }}">
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <header class="main-header">
        <!-- Logo -->
        <a href="{{ route('dashboard') }}" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>A</b>LT</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>Admin</b>LTE</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Notifications: style can be found in dropdown.less -->
              <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-bell-o"></i>
                  <span class="label label-warning">10</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 10 notifications</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li>
                        <a href="#">
                          <i class="fa fa-users text-aqua"></i> 5 new members joined today
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the
                          page and may cause design problems
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-users text-red"></i> 5 new members joined
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-user text-red"></i> You changed your username
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="#">View all</a></li>
                </ul>
              </li>
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="{{ asset('dist/img/user2-160x160.jpg') }}" class="user-image" alt="User Image">
                  <span class="hidden-xs">Alexander Pierce</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <img src="{{ asset('dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
                    <p>
                      Alexander Pierce - Web Developer
                      <small>Member since Nov. 2012</small>
                    </p>
                  </li>
                  <!-- Menu Body -->
                  <li class="user-body">
                    <div class="row">
                      <div class="col-xs-4 text-center">
                        <a href="#">Followers</a>
                      </div>
                      <div class="col-xs-4 text-center">
                        <a href="#">Sales</a>
                      </div>
                      <div class="col-xs-4 text-center">
                        <a href="#">Friends</a>
                      </div>
                    </div>
                    <!-- /.row -->
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="#" class="btn btn-default btn-flat">Profile</a>
                    </div>
                    <div class="pull-right">
                      <a href="#" class="btn btn-default btn-flat">Sign out</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>

      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="{{ asset('dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
              <p>Alexander Pierce</p>
              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>
          <!-- search form -->
          <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
          </form>
          <!-- /.search form -->
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu" data-widget="tree">
            <li>
              <a href="pages/widgets.html">
                <i class="fa fa-th"></i> <span>Widgets</span>
                <span class="pull-right-container">
                  <small class="label pull-right bg-green">new</small>
                </span>
              </a>
            </li>
            <li class="treeview @if (Illuminate\Support\Str::contains(url()->current(), 'product')) active @endif">
              <a href="#">
                <i class="fa fa-pie-chart"></i>
                <span>Products</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{ route('dashboard.product')}}"><i class="fa fa-circle-o"></i> Manage all products</a></li>
                <li><a href="{{ route('dashboard.add-product') }}"><i class="fa fa-circle-o"></i> Add new product</a></li>
              </ul>
            </li>
            <li><a href="https://adminlte.io/docs"><i class="fa fa-book"></i> <span>Documentation</span></a></li>
            <li class="header">LABELS</li>
            <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          @yield('breadcrumbs')
        </section>
        <!-- Main content -->
        <section class="content">
          @yield('content')
        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 2.4.13
        </div>
        <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE</a>.</strong> All rights
        reserved.
      </footer>
      <!-- jQuery 3 -->
      <script src="{{ asset('bower_components/jquery/dist/jquery.min.js') }}"></script>
      <!-- jQuery UI 1.11.4 -->
      <script src="{{ asset('bower_components/jquery-ui/jquery-ui.min.js') }}"></script>
      <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
      <script>
      $.widget.bridge('uibutton', $.ui.button);
      </script>
      <!-- Bootstrap 3.3.7 -->
      <script src="{{ asset('bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
      <!-- Bootstrap WYSIHTML5 -->
      <script src="{{ asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
      <!-- AdminLTE App -->
      <script src="{{ asset('dist/js/adminlte.min.js') }}"></script>
      <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
      <script src="{{ asset('dist/js/pages/dashboard.js') }}"></script>

      @yield('javascript')
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <title>Toko Online</title>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);function hideURLbar(){ window.scrollTo(0,1); } </script>

    <!-- //for-mobile-apps -->
    <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/style.css') }}" rel="stylesheet" type="text/css" />
    <!-- font-awesome icons -->
    <link href="{{ asset('css/font-awesome.css') }}" rel="stylesheet" type="text/css" />
    <!-- //font-awesome icons -->
    <!-- js -->
    <script src="{{ asset('js/jquery-1.11.1.min.js') }}"></script>
    <!-- //js -->
    <link href='//fonts.googleapis.com/css?family=Ubuntu:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <!-- start-smoth-scrolling -->
    <script type="text/javascript" src="{{ asset('js/move-top.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/easing.js') }}"></script>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $(".scroll").click(function(event){
                event.preventDefault();
                $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
            });
        });
    </script>
    <!-- start-smoth-scrolling -->
</head>
<body>
  <!-- header -->
  <div class="agileits_header">
    <div class="l_offers">
      <a href="products.html">Today's special Offers !</a>
    </div>
    <div class="l_search">
      <form action="#" method="post">
        <input type="text" name="Product" value="Search a product..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search a product...';}" required="">
        <input type="submit" value=" ">
      </form>
    </div>
    <div class="product_list_header">
      <form action="#" method="post" class="last">
        <fieldset>
          <input type="hidden" name="cmd" value="_cart" />
          <input type="hidden" name="display" value="1" />
          <input type="submit" name="submit" value="View your cart" class="button" />
        </fieldset>
      </form>
    </div>
    <div class="l_header_right">
      <ul>
        <li class="dropdown profile_details_drop">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user" aria-hidden="true"></i><span class="caret"></span></a>
          <div class="mega-dropdown-menu">
            <div class="ls_vegetables">
              <ul class="dropdown-menu drp-mnu">
                <li><a href="login.html">Login</a></li>
                <li><a href="login.html">Sign Up</a></li>
              </ul>
            </div>
          </div>
        </li>
      </ul>
    </div>
    <div class="l_header_right1">
      <h2><a href="mail.html">Contact Us</a></h2>
    </div>
    <div class="clearfix"> </div>
  </div>

  <!-- script-for sticky-nav -->
  <script>
  $(document).ready(function() {
    var navoffeset=$(".agileits_header").offset().top;
    $(window).scroll(function(){
      var scrollpos=$(window).scrollTop();
      if (scrollpos >=navoffeset){
          $(".agileits_header").addClass("fixed");
      } else {
          $(".agileits_header").removeClass("fixed");
      }
    });
  });
  </script>

  <!-- //script-for sticky-nav -->
  <div class="logo_products">
      <div class="container">
          <div class="ls_logo_products_left">
              <h1><a href="index.html"><span>Ada</span> Store</a></h1>
          </div>
          <div class="ls_logo_products_left1">
              <ul class="special_items">
                  <li><a href="events.html">Events</a><i>/</i></li>
                  <li><a href="about.html">About Us</a><i>/</i></li>
                  <li><a href="products.html">Best Deals</a><i>/</i></li>
                  <li><a href="services.html">Services</a></li>
              </ul>
          </div>
          <div class="ls_logo_products_left1">
              <ul class="phone_email">
                  <li><i class="fa fa-phone" aria-hidden="true"></i>(+0123) 234 567</li>
                  <li><i class="fa fa-envelope-o" aria-hidden="true"></i><a href="mailto:store@grocery.com">store@grocery.com</a></li>
              </ul>
          </div>
          <div class="clearfix"> </div>
      </div>
  </div>
  <!-- //header -->
  @yield('products-breadcrumb')
  <!-- banner -->
  <div class="banner">
    <div class="l_banner_nav_left">
      <nav class="navbar nav_bottom">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header nav_2">
          <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
          <ul class="nav navbar-nav nav_1">
            <li><a href="products.html">Branded Foods</a></li>
            <li><a href="household.html">Households</a></li>
            <li class="dropdown mega-dropdown active">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Veggies & Fruits<span class="caret"></span></a>
              <div class="dropdown-menu mega-dropdown-menu ls_vegetables_menu">
                <div class="ls_vegetables">
                  <ul>
                    <li><a href="vegetables.html">Vegetables</a></li>
                    <li><a href="vegetables.html">Fruits</a></li>
                  </ul>
                </div>
              </div>
            </li>
            <li><a href="kitchen.html">Kitchen</a></li>
            <li><a href="short-codes.html">Short Codes</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Beverages<span class="caret"></span></a>
              <div class="dropdown-menu mega-dropdown-menu ls_vegetables_menu">
                <div class="ls_vegetables">
                  <ul>
                    <li><a href="drinks.html">Soft Drinks</a></li>
                    <li><a href="drinks.html">Juices</a></li>
                  </ul>
                </div>
              </div>
            </li>
            <li><a href="pet.html">Pet Food</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Frozen Foods<span class="caret"></span></a>
              <div class="dropdown-menu mega-dropdown-menu ls_vegetables_menu">
                <div class="ls_vegetables">
                  <ul>
                    <li><a href="frozen.html">Frozen Snacks</a></li>
                    <li><a href="frozen.html">Frozen Nonveg</a></li>
                  </ul>
                </div>
              </div>
            </li>
            <li><a href="bread.html">Bread & Bakery</a></li>
          </ul>
          </div><!-- /.navbar-collapse -->
        </nav>
      </div>
      <div class="l_banner_nav_right">
        @yield('banner-content')
      </div>
      <div class="clearfix"></div>
    </div>
    <!-- banner -->
    @yield('content')
  <!-- //fresh-vegetables -->
  <!-- newsletter -->
  <div class="newsletter">
    <div class="container">
      <div class="agile_newsletter_left">
        <h3>sign up for our newsletter</h3>
      </div>
      <div class="agile_newsletter_right">
        <form action="#" method="post">
          <input type="email" name="Email" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
          <input type="submit" value="subscribe now">
        </form>
      </div>
      <div class="clearfix"> </div>
    </div>
  </div>
  <!-- //newsletter -->
  <!-- footer -->
  <div class="footer">
    <div class="container">
      <div class="col-md-3 footer_grid">
        <h3>information</h3>
        <ul class="footer_grid_list">
          <li><a href="events.html">Events</a></li>
          <li><a href="about.html">About Us</a></li>
          <li><a href="products.html">Best Deals</a></li>
          <li><a href="services.html">Services</a></li>
          <li><a href="short-codes.html">Short Codes</a></li>
        </ul>
      </div>
      <div class="col-md-3 footer_grid">
        <h3>policy info</h3>
        <ul class="footer_grid_list">
          <li><a href="faqs.html">FAQ</a></li>
          <li><a href="privacy.html">privacy policy</a></li>
          <li><a href="privacy.html">terms of use</a></li>
        </ul>
      </div>
      <div class="col-md-3 footer_grid">
        <h3>what in stores</h3>
        <ul class="footer_grid_list">
          <li><a href="pet.html">Pet Food</a></li>
          <li><a href="frozen.html">Frozen Snacks</a></li>
          <li><a href="kitchen.html">Kitchen</a></li>
          <li><a href="products.html">Branded Foods</a></li>
          <li><a href="household.html">Households</a></li>
        </ul>
      </div>
      <div class="col-md-3 footer_grid">
        <h3>twitter posts</h3>
        <ul class="footer_grid_list1">
          <li><label class="fa fa-twitter" aria-hidden="true"></label><i>01 day ago</i><span>Non numquam <a href="#">http://sd.ds/13jklf#</a>
          eius modi tempora incidunt ut labore et
          <a href="#">http://sd.ds/1389kjklf#</a>quo nulla.</span></li>
          <li><label class="fa fa-twitter" aria-hidden="true"></label><i>02 day ago</i><span>Con numquam <a href="#">http://fd.uf/56hfg#</a>
          eius modi tempora incidunt ut labore et
          <a href="#">http://fd.uf/56hfg#</a>quo nulla.</span></li>
        </ul>
      </div>
      <div class="clearfix"> </div>
      <div class="agile_footer_grids">
        <div class="col-md-3 footer_grid agile_footer_grids_footer">
          <div class="footer_grid_bottom">
            <h4>100% secure payments</h4>
            <img src="images/card.png" alt=" " class="img-responsive" />
          </div>
        </div>
        <div class="col-md-3 footer_grid agile_footer_grids_footer">
          <div class="footer_grid_bottom">
            <h5>connect with us</h5>
            <ul class="agileits_social_icons">
              <li><a href="#" class="facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
              <li><a href="#" class="twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
              <li><a href="#" class="google"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
              <li><a href="#" class="instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
              <li><a href="#" class="dribbble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
            </ul>
          </div>
        </div>
        <div class="clearfix"> </div>
      </div>
      <div class="wthree_footer_copy">
        <p>© 2016 Toko Online. All rights reserved</p>
      </div>
    </div>
  </div>
  <!-- //footer -->
  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>
  <script>
  $(document).ready(function(){
      $(".dropdown").hover(
          function() {
              $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
              $(this).toggleClass('open');
          },
          function() {
              $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
              $(this).toggleClass('open');
          }
      );
  });
  </script>
  <!-- here stars scrolling icon -->
  <script type="text/javascript">
      $(document).ready(function() {
          /*
              var defaults = {
              containerID: 'toTop', // fading element id
              containerHoverID: 'toTopHover', // fading element hover id
              scrollSpeed: 1200,
              easingType: 'linear'
              };
          */

          $().UItoTop({ easingType: 'easeOutQuart' });

          });
  </script>
  <!-- //here ends scrolling icon -->
  <script src="js/minicart.js"></script>
  <script>
    paypal.minicart.render();

    paypal.minicart.cart.on('checkout', function (evt) {
        var items = this.items(),
            len = items.length,
            total = 0,
            i;

        // Count the number of each item in the cart
        for (i = 0; i < len; i++) {
            total += items[i].get('quantity');
        }

        if (total < 3) {
            alert('The minimum order quantity is 3. Please add more to your shopping cart before checking out');
            evt.preventDefault();
        }
    });
  </script>
</body>
</html>